# index.html configmap for /app/templates/index.html
apiVersion: v1
kind: ConfigMap
metadata:
  name: bb-configmap
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>BB - Page View Counter</title>
        <!-- tailwind -->
        <script src="https://cdn.tailwindcss.com"></script>
    </head>
    <body class="bg-gray-900 text-white">
        <!-- full page centered container and centered text counter -->
        <div class="flex justify-center items-center h-screen">
            <div class="text-center">
                <h1 class="text-3xl font-bold underline">
                    Bulut Bili≈üimciler <br> View Counter
                </h1>
                <p class="text-5xl font-bold">
                    {{.Counter}}
                </p>
            </div>
    </body>
    </html>