---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bb-app
  template:
    metadata:
      labels:
        app: bb-app
    spec:
      containers:
        - name: webserver-simples
          image: docker.io/alperreha/cn-turkey-demo:1.0.2
          ports:
            - containerPort: 4040
          env:
            - name: APP_PORT
              value: "4040"
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: bb-cache-secret
                  key: REDIS_URL
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bb-cache-secret
                  key: REDIS_PASSWORD
      #     # add configmap "bb-configmap-index" to "/app/templates" folder
          volumeMounts:
            - name: custom-index
              mountPath: /app/templates
      volumes:
        - name: custom-index
          configMap:
            name: bb-configmap-index